# INPUT_SIZE = 
NUM_CLASSES = 10
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 2e-4
BATCH_SIZE = 10
NUM_EPOCHS = 1

# Dataset
# TRAIN_DATA_DIR = "dataset/"
# VAL_DATA_DIR = ""
# TEST_DATA_DIR =""

# Compute related
ACCELERATOR = "gpu"
DEVICES = [0]
PRECISION = 16