wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714660885.0
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      - 103
      3:
      - 17
      - 23
      - 37
      4: 3.10.10
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
